### PR TITLE
Restructure to support github smartthings integration

### PR DESCRIPTION
**Pull request by jmaxxz**
Background information:
http://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html

Why this PR matters:
This allows users to use the device types and smartapps in this repository in a way which allows for easy updating.

### CODE REVIEW

**Comment by jmaxxz** [comment]
Assuming the general idea here is acceptable I will update the `Readme` to instead provide directions on using the github integration to install the smartapp/devices.

**Comment by endlesscoil** [comment]
Seems like a very useful thing to have.  Go ahead and update the README and I'll merge it in.  Thanks!

**Comment by jmaxxz** [comment]
readme updated

**Comment by jmaxxz** [comment]
readme updated

**Pull request merged**
